# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos8"

   config.vm.network "private_network", ip: "192.168.56.4"

   config.vm.network "public_network"

   config.vm.synced_folder "../staticPage", "/vagrant"

   config.vm.provider "virtualbox" do |vb|
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
   end
  #
   config.vm.provision "shell", inline: <<-SHELL
     yum install httpd wget unzip -y
     systemctl start httpd
     systemctl enable httpd
     cd /tmp/
     wget https://www.tooplate.com/zip-templates/2129_crispy_kitchen.zip
     unzip -o 2129_crispy_kitchen.zip
     cp -r 2129_crispy_kitchen/* /var/www/html/
     systemctl restart httpd
   SHELL
end
