Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.network "private_network", ip: "192.168.56.3"

  config.vm.synced_folder "../simpleApp", "/opt/docker"


  config.vm.provider "virtualbox" do |vb|
  end
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    sudo apt-get install \
    ca-certificates \
    curl \
    zip \
    unzip \
    gnupg \
    lsb-release -y
    sudo mkdir -p /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    sudo apt-get update
    sudo apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin -y
    sudo service docker start
    
    # Run container
    cd /opt/docker
    docker compose up -d  
  SHELL
end
