pipeline {
    agent {
        label 'builtinNode'
    }
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f jenkins/java-tomcat-sample/pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
        agent {
        label 'testNode'
        }
        stage('Create Tomcat Image') {
            steps {
                sh '''
                original_pwd=$(pwd -P)
                cd jenkins/java-tomcat-sample
                docker build -t localtomcatimg:$BUILD_NUMBER .
                cd $original_pwd
                sh '''
            }
        }
        stage('Deploy Staging Env'){
            steps{
                build job: 'deployTomcatApPipeline'
            }
        }
    }
}