# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"

  config.vm.network "private_network", ip: "192.168.56.2"
  
  config.vm.synced_folder "../vagrantDisk", "/vagrant"

   config.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
     vb.cpus = 2
   end
   config.disksize.size = '60GB'
end
