# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX_NAME = "ubuntu/focal64"
MEMORY = "4096"
MACHINE_IP = "192.168.56.11"
CPUS = 2

Vagrant.configure("2") do |config|
  config.vm.box = BOX_NAME

   config.vm.network "private_network", ip: MACHINE_IP

   config.vm.provider "virtualbox" do |vb|
     vb.memory = MEMORY
     vb.cpus = CPUS
   end
  
   config.vm.provision "shell", inline: <<-SHELL
   	echo "Installing dependencies ..."
	sudo apt-get update
	echo Installing Docker...
	curl -sSL https://get.docker.com/ | sh
	sudo usermod -aG docker vagrant
   SHELL
end
