Vagrant.configure("2") do |config|
    config.vm.provision "shell", inline: "echo Hello"
  
    config.vm.define "web" do |web|
      web.vm.box = "ubuntu/focal64"
      web.vm.network "private_network", ip: "192.168.56.6"
      web.vm.synced_folder "../multiVM", "/vagrant"
      web.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 2
        end
        web.vm.provision "shell", inline: <<-SHELL
        apt update
        apt install apache2 wget unzip -y
        systemctl start apache2
        systemctl enable apache2
        cd /tmp/
        wget https://www.tooplate.com/zip-templates/2129_crispy_kitchen.zip
        unzip -o 2129_crispy_kitchen.zip
        cp -r 2129_crispy_kitchen/* /var/www/html/
        systemctl restart apache2
      SHELL
    end
  
    config.vm.define "db" do |db|
      db.vm.box = "generic/centos8"
      db.vm.network "private_network", ip: "192.168.56.7"
      db.vm.provider "virtualbox" do |vb|
           vb.memory = "1024"
           vb.cpus = "1"
         end
        db.vm.provision "shell", inline: <<-SHELL
        yum update
        yum install mariadb-server -y
        systemctl start mariadb
        systemctl enable mariadb 
        SHELL
  end
end